### PR TITLE
#1 add complete workflow as example

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #1

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP confirmed that GHA is on.

**Comment by CAMOBAP** [comment]
@ronaldtse thanks, it works now

**Comment by CAMOBAP** [comment]
Windows issue will be addressed separatelly https://github.com/metanorma/chocolatey-metanorma/issues/72

**Comment by ronaldtse** [comment]
Thank you @CAMOBAP !

**Pull request merged**
